name: cxo-ui pipeline
on:
  push:
    branches:
      - main
      - mybranch

jobs:
  CheckBranch:
    name: Test Branch
    runs-on: ubuntu-latest

    timeout-minutes: 2

    steps:
      - name: Take manual approval for master branch
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}

  Check_container_status:
    needs: [CheckBranch]
    runs-on: ubuntu-latest
    steps:
      - name: Login into EC2 using SSH
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key -o 'StrictHostKeyChecking=no' ${USER_NAME}@${HOSTNAME} "
          if [ \"\$(docker inspect -f '{{.State.Restarting}}' eager_cray\" == \"true\" ]; then
            echo \"Container is restarting\"
            exit 1
          else
            echo \"Container is running\"
          fi "
