name: Check Container Status
on:
  workflow_dispatch:
    inputs:
      container_name:
        description: 'Name of the container'
        required: true

jobs:
  check_container_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Container Status
        env:
          CONTAINER_NAME: ${{ github.event.inputs.container_name }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key -o 'StrictHostKeyChecking=no' ${SSH_USERNAME}@${SSH_HOST} "
          if [ \"\$(docker inspect -f '{{.State.Status}}' ${CONTAINER_NAME})\" == \"running\" ]; then
            echo \"Container is running\"
          else
            echo \"Container is not running\"
            exit 1
          fi"
