name: GitOps - Check Container Status
on:
  push:
    branches:
      - main

jobs:
  check_container_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Retrieve Container ID and Status
        run: |
          # Replace with your SSH command to retrieve the container ID and status
          # Example:
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@3.16.143.82 "CONTAINER_ID=\$(docker ps -qf 'name=some-nginx')
          CONTAINER_STATUS=\$(docker inspect -f '{{.State.Status}}' \$CONTAINER_ID)
          echo \"::set-output name=container_id::\$CONTAINER_ID\"
          echo \"::set-output name=container_status::\$CONTAINER_STATUS\"          

      - name: Check Container Status
        run: |
          # Retrieve the container ID and status from the previous step output
          CONTAINER_ID=${{ steps.retrieve.outputs.container_id }}
          CONTAINER_STATUS=${{ steps.retrieve.outputs.container_status }}

          echo "Container ID: $CONTAINER_ID"
          echo "Container Status: $CONTAINER_STATUS"

          # Additional steps or actions based on the container status
          if [[ $CONTAINER_STATUS == "running" ]]; then
            echo "Container is running"
            # Additional steps or actions to perform if the container is running
          else
            echo "Container is not running"
            # Additional steps or actions to perform if the container is not running
          fi
