name: Check Container Status
on:
  workflow_dispatch:
    inputs:
      container_name:
        description: 'Name of the container'
        required: true
      ssh_host:
        description: 'SSH host for the user'
        required: true
      ssh_username:
        description: 'SSH username for the user'
        required: true

jobs:
  check_container_status:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Container Status
        env:
          CONTAINER_NAME: ${{ github.event.inputs.container_name }}
          SSH_HOST: ${{ github.event.inputs.ssh_host }}
          SSH_USERNAME: ${{ github.event.inputs.ssh_username }}
        run: |
          ssh -o 'StrictHostKeyChecking=no' ${SSH_USERNAME}@${SSH_HOST} "
          if [ \"\$(docker inspect -f '{{.State.Status}}' ${CONTAINER_NAME})\" == \"running\" ]; then
            echo \"Container is running\"
          else
            echo \"Container is not running\"
            exit 1
          fi"
